language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-head
  - ree
script: bundle exec rspec spec
before_install:
  - curl -O http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/libsqlite3-0_3.8.6-1_amd64.deb
  - curl -O http://mirrors.kernel.org/ubuntu/pool/main/s/sqlite3/sqlite3_3.8.6-1_amd64.deb
  - sudo dpkg -i libsqlite3-0_3.8.6-1_amd64.deb sqlite3_3.8.6-1_amd64.deb
